version: '3.8'
services:
  blue:
    container_name: blue
    image: jisoo708/dobby
    expose:
      - 8080
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Seoul
  green:
    container_name: green
    image: jisoo708/dobby
    expose:
      - 8080
    ports:
      - "8082:8080"
    environment:
      - TZ=Asia/Seoul
