name: "Add Pull Request Auto Template"
on:
  pull_request:
    branches:
      - dev

jobs:
  update_pr_templates:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2 # https://github.com/tzkhan/pr-update-action
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: 'dev'
          head-branch-regex: 'ys-\d+' # Branch에서 Ticket Regex
          title-template: '[%headbranch%] ' # PR Title Prefix 템플릿 (티켓 번호) (ex: [YS-1234] ~ )
          body-template: | # PR Body suffix 템플릿 (지라 링크)
            ## 🔗 Jira 티켓

            ---
            https://yappsocks.atlassian.net/browse/%headbranch%
          body-update-action: 'suffix'
